// Code generated by entc, DO NOT EDIT.

package job

import (
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/lht102/message-playground/jobworker"
)

const (
	// Label holds the string label denoting the job type in the database.
	Label = "job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequestUUID holds the string denoting the request_uuid field in the database.
	FieldRequestUUID = "request_uuid"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the job in the database.
	Table = "jobs"
)

// Columns holds all SQL columns for job fields.
var Columns = []string{
	FieldID,
	FieldRequestUUID,
	FieldState,
	FieldDescription,
	FieldCompletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s jobworker.JobState) error {
	switch s {
	case "QUEUED", "PROCESSING", "COMPLETED":
		return nil
	default:
		return fmt.Errorf("job: invalid enum value for state field: %q", s)
	}
}
