run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - gomodguard
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - goheader
    - goimports
    - staticcheck
    - goprintffuncname
    - gosec
    - importas
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goerr113
        - bodyclose
